apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-resources
  namespace: k8s-program
data:
  resource-init.sql: |
    CREATE TABLE IF NOT EXISTS resources (
      id SERIAL PRIMARY KEY,
      blob BIGINT NOT NULL
    );