apiVersion: v1
kind: PersistentVolume
metadata:
  name: songs-pv
  namespace: k8s-program
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data/songs"