apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: resources-service
data:
  RESOURCES_MS_NAME: {{ .Values.config.resourcesMsName }}
  RESOURCES_MS_PORT: "{{ .Values.config.resourcesMsPort }}"
  SONGS_MS_URL: {{ .Values.config.songsMsUrl }}
  SONGS_MS_PORT: "{{ .Values.config.songsMsPort }}"
  RESOURCES_DB_URL: {{ .Values.config.dbUrl }}
  RESOURCES_DB_PORT: "{{ .Values.config.dbPort }}"
  EUREKA_URI: {{ .Values.config.eurekaUri }}
