replicaCount: 2
namespace: k8s-program

containerName: resources-ms

image:
  repository: resources-image
  tag: "1.0.0"
  pullPolicy: Never

configMapName: resources-app-config

service:
  port: 8080
  targetPort: 8080

config:
  resourcesMsName: resources-ms
  resourcesMsPort: "8080"
  songsMsUrl: songs-ms
  songsMsPort: "8080"
  dbUrl: resources-db
  dbPort: "5432"
  eurekaUri: eureka-server
