apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.db.initConfigMap }}
  namespace: {{ .Release.Namespace }}
data:
  song-init.sql: |
    CREATE TABLE IF NOT EXISTS songs (
      id SERIAL PRIMARY KEY,
      name VARCHAR(255),
      artist VARCHAR(255),
      album VARCHAR(255),
      length VARCHAR(255),
      resource_id INT,
      year VARCHAR(4),
      genre VARCHAR(255)
    );
