apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  namespace: {{ .Release.Namespace }}
  labels:
    { { - include "songs-service.labels" . | nindent 4 } }
data:
  SONGS_MS_NAME: {{ .Values.config.songsMsName }}
  SONGS_MS_PORT: "{{ .Values.config.songsMsPort }}"
  SONGS_DB_URL: {{ .Values.config.dbUrl }}
  SONGS_DB_PORT: "{{ .Values.config.dbPort }}"
  EUREKA_URI: {{ .Values.config.eurekaUri }}
