apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
  labels:
    app.kubernetes.io/managed-by: Helm
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.pv.storage }}
  accessModes:
    - {{ .Values.pv.accessMode }}
  persistentVolumeReclaimPolicy: {{ .Values.pv.reclaimPolicy }}
  storageClassName: {{ .Values.pv.storageClass }}
  hostPath:
    path: {{ .Values.pv.path }}
