apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-deployment
  namespace: k8s-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resources-ms
  template:
    metadata:
      labels:
        app: resources-ms
    spec:
      containers:
        - name: resources-ms
          image: resources-image:1.0.0
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: app-config