apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs-deployment
  namespace: k8s-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: songs-ms
  template:
    metadata:
      labels:
        app: songs-ms
    spec:
      containers:
        - name: songs-ms
          image: songs-image:1.0.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: app-config
          volumeMounts:
            - mountPath: /mnt/data
              name: songs-storage
      volumes:
        - name: songs-storage
          persistentVolumeClaim:
            claimName: songs-pvc