apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.db.initConfigMap }}
  namespace: {{ .Release.Namespace }}
data:
  resource-init.sql: |
    CREATE TABLE IF NOT EXISTS resources (
      id SERIAL NOT NULL,
      blob BYTEA,
      PRIMARY KEY (id)
    );
