apiVersion: v1
kind: Service
metadata:
  name: songs-ms
  namespace: k8s-program
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
  selector:
    app: songs-ms